.TH TRIZEN "1" "August 2018" "1.0.1" "User Commands"

.SH NAME
trizen \- trizen is a lightweight wrapper for AUR, written in Perl.

.SH "SYNOPSIS"
.sp
\fItrizen\fR <operation> [options] [targets]

.SH "OPERATIONS"
.PP
\fB\-S, \-\-sync\fR
.RS 4
Synchronize packages. Packages are installed directly from the remote repositories or from the AUR, including all dependencies required to run the packages.
.RE
.PP
\fB\-C, \-\-comments\fR
.RS 4
Display AUR comments for a package.
.RE
.PP
\fB\-G, \-\-get\fR
.RS 4
Clone an AUR package in the current directory.
.RE
.PP
\fB\-R, \-\-remove\fR
.RS 4
Remove package(s) from the system. See: \fIpacman -Rh\fR
.RE
.PP
\fB\-Q, \-\-query\fR
.RS 4
Query the package database. See: \fIpacman -Qh\fR
.RE
.PP
\fB\-F, \-\-files\fR
.RS 4
Query the files database. See: \fIpacman -Fh\fR
.RE
.PP
\fB\-D, \-\-database\fR
.RS 4
Operate on the package database. See: \fIpacman -Dh\fR
.RE
.PP
\fB\-T, \-\-deptest\fR
.RS 4
Check dependencies. See: \fIpacman -Th\fR
.RE
.PP
\fB\-U, \-\-upgrade\fR
.RS 4
Install built packages from \fI--clone-dir\fR or \fI`pwd`\fR. See: \fIpacman -Uh\fR

.RE
.SH "OPTIONS"
.PP
\fB\-q, \-\-quiet\fR
.RS 4
Display minimal output.
.RE
.PP
\fB\-r, \-\-regular\fR
.RS 4
Perform only regular \fIpacman\fR operations (the opposite of \fI--aur\fR).
.RE
.PP
\fB\-\-stats\fR
.RS 4
Display statistics for the installed packages.
.RE
.PP
\fB\-\-nocolors\fR
.RS 4
Disable ANSI colors.
.RE
.PP
\fB\-\-debug\fR
.RS 4
Enable verbose mode.

.RE
.SH "SYNC OPTIONS (APPLY TO \FI-S\FR)"
.PP
\fB\-s, \-\-search\fR
.RS 4
Search for packages. By default, it includes packages from the pacman repos and from the AUR.
.RE
.PP
\fB\-i, \-\-info\fR
.RS 4
Display info for packages.
.RE
.PP
\fB\-m, \-\-maintainer\fR
.RS 4
Display the AUR packages maintained by a given \fIusername\fR.
.RE
.PP
\fB\-p, \-\-pkgbuild\fR
.RS 4
Display the PKGBUILD of a given AUR package. For repo packages, it displays the download link.
.RE
.PP
\fB\-l, \-\-local\fR
.RS 4
Build and install packages from the current directory. This option is best used in combination with \fI-G\fR. After A package is cloned in the current directory, the user can inspect or edit the build files, then \fI-Sl <pkgname>\fR will build and install the package, without pulling new changes from the AUR.
.RE
.PP
\fB\-u, \-\-sysupgrade\fR
.RS 4
Upgrades all packages that are out-of-date.
.RE
.PP
\fB\-y, \-\-refresh\fR
.RS 4
Refresh package databases.
.RE
.PP
\fB\-c, \-\-clean\fR
.RS 4
Clean the cache directory of \fIpacman\fR and \fItrizen\fR. Add \fI-r\fR to clean only pacman's cache, or \fI-a\fR to clean only trizen's cache.
.RE
.PP
\fB\-a, \-\-aur\fR
.RS 4
Only AUR operations.
.RE
.PP
\fB\-\-devel\fR
.RS 4
Update VCS packages during \fI-Su\fR.
.RE
.PP
\fB\-\-show-ood\fR
.RS 4
Show out-of-date flagged packages during \fI-Su\fR.
.RE
.PP
\fB\-\-noinfo\fR
.RS 4
Do not display package information after cloning.
.RE
.PP
\fB\-\-nopull\fR
.RS 4
Do not \fI`git pull`\fR new changes from the AUR when the build files of a package already exist locally.
.RE
.PP
\fB\-\-noedit\fR
.RS 4
Do not prompt to edit the build files of packages.
.RE
.PP
\fB\-\-nobuild\fR
.RS 4
Do not build packages (implies \fI--noedit\fR).
.RE
.PP
\fB\-\-noinstall\fR
.RS 4
Do not install packages after building.
.RE
.PP
\fB\-\-noconfirm\fR
.RS 4
Do not ask for any confirmation.
.RE
.PP
\fB\-\-needed\fR
.RS 4
Do not reinstall up-to-date packages.
.RE
.PP
\fB\-\-asdeps\fR
.RS 4
Install packages as dependencies (non-explicit).
.RE
.PP
\fB\-\-asexplicit\fR
.RS 4
Install packages as explicitly installed.
.RE
.PP
\fB\-\-force\fR
.RS 4
Pass the \fI--force\fR argument to \fIpacman\fR.
.RE
.PP
\fB\-\-force\fR
.RS 4
Pass the \fI--skipinteg\fR argument to \fImakepkg\fR.
.RE
.PP
\fB\-\-movepkg\fR
.RS 4
Move built packages in pacman's cache directory.
.RE
.PP
\fB\-\-movepkg-dir='...'\fR
.RS 4
Move built packages into this directory (implies \fI--movepkg\fR).
.RE
.PP
\fB\-\-clone-dir='...'\fR
.RS 4
Directory where to clone and build packages.
.RE
.PP
\fB\-\-editor='...'\fR
.RS 4
Editor command used to edit the build files of AUR packages. The default editor is \fI$VISUAL\fR or \fI$EDITOR\fR (in this order).
.RE
.PP
\fB\-\-pager-mode\fR
.RS 4
Display the build files of packages in pager mode.
.RE
.PP
\fB\-\-pager='...'\fR
.RS 4
Pager command used to display the build files of packages (with \fI--pager-mode\fR). The default pager is \fI$PAGER\fR.
.RE
.PP
\fB\-\-ignore='...'\fR
.RS 4
Space-separated list of packages to ignore during \fI-Su\fR.
.RE

.RE
.SH "GET OPTIONS (APPLY TO \FI-G\FR)"
.PP
\fB\-d, \-\-with\-deps\fR
.RS 4
Clone a package along with all its AUR dependencies that are not already installed.
.RE

.SH "INTERACTIVE MODE"
.PP
Search and select packages to install, using the following syntax:

.RS 4
\fItrizen [keywords]\fR
.RE
.PP
By default, the results include both repo and AUR packages. Add \fI--regular\fR or \fI--aur\fR to search only for repo or AUR packages, respectively.

.SH "EXAMPLES"
.nf
\ \ trizen\ \-S\ \ <package>\ \ \ \ \ #\ install\ <package>
\ \ trizen\ \-Ss\ <keyword>\ \ \ \ \ #\ search\ for\ <keyword>
\ \ trizen\ \-Si\ <package>\ \ \ \ \ #\ show\ info\ about\ <package>

\ \ trizen\ \-G\ \ <package>\ \ \ \ \ #\ clones\ <package>
\ \ trizen\ \-Gd\ <package>\ \ \ \ \ #\ clones\ <package>\ along\ with\ its\ AUR\ dependencies

.SH CONFIGURATION
Configuration file: ~/.config/trizen/trizen.conf

.SH "CONFIGURATION OPTIONS"
.PP
Each configuration key can be used an a command-line argument, by preceding it with `\fI--\fR` and (optionally) replacing underscores (`\fI_\fR`) with dashes (`\fI-\fR`).

For example:

.RS 4
\fItrizen --stats --packages-in-stats=50\fR
.RE
.PP
The above command will display 50 packages in \fI--stats\fR.

.SH AUTHOR
Daniel Șuteu <trizen@protonmail.com>

.SH "SEE ALSO"
Upstream repository: https://github.com/trizen/trizen
